<a href="https://colab.research.google.com/github/Neethuharii/Foundatin-of-ML/blob/main/Data%20Analysis%20with%20Python/Numerical_Computing_with_Python_and_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Working with numerical data

yield_of_apples = w1 * temperature + w2 * rainfall + w3 * humidity

In [3]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [4]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [5]:
kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3
kanto_yield_apples

56.8

In [6]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]            #The three numbers in each vector represent the temperature, rainfall, and humidity data, respectively.


In [7]:
#We can also represent the set of weights used in the formula as a vector.

weights = [w1, w2, w3]

In [8]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

In [9]:
crop_yield(kanto, weights)

56.8

In [10]:
crop_yield(johto, weights)

76.9

In [11]:
crop_yield(hoenn, weights)

81.9

###Going from Python lists to Numpy arrays

In [12]:
import numpy as np

In [13]:
kanto=np.array([73,67,43])
kanto

array([73, 67, 43])

In [14]:
weights=np.array([w1,w2,w3])
weights

array([0.3, 0.2, 0.5])

####Operating on Numpy arrays

In [15]:
np.dot(kanto,weights)

56.8

####Benefits of using Numpy array

* Ease of use
* Performance

####Working with CSV data files


In [16]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv',
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7a67a9af6890>)

To read this file into a numpy array, we can use the genfromtxt function.

In [17]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [18]:
yields = climate_data @ weights     #perform a matrix multiplication using the @ operator to predict the yield of apples for the entire dataset using a given set of weights.
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

####Arithmetic operations, broadcasting and comparison



In [19]:
import numpy as np

In [20]:
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 1, 2, 3]])


In [21]:
arr3 = np.array([[11, 12, 13, 14],
                 [15, 16, 17, 18],
                 [19, 11, 12, 13]])

In [22]:
arr2+3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [23]:
arr2-arr3

array([[-10, -10, -10, -10],
       [-10, -10, -10, -10],
       [-10, -10, -10, -10]])

In [24]:
arr2/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [25]:
arr2 * arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

####Array Broadcasting

Numpy arrays also support broadcasting, allowing arithmetic operations between two arrays with different numbers of dimensions but compatible shapes.

In [26]:
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 1, 2, 3]])

In [27]:
arr2.shape

(3, 4)

In [28]:
arr4 = np.array([4, 5, 6, 7])

In [29]:
arr4.shape

(4,)

In [30]:
arr2+arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

####Array Comparison

In [31]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [32]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [33]:
arr1!= arr2

array([[ True, False, False],
       [ True,  True, False]])

In [35]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

array comparison is frequently used to count the number of equal elements in two arrays using the sum method. Remember that True evaluates to 1 and False evaluates to 0 when booleans are used in arithmetic operations.

In [37]:
(arr1 == arr2).sum()

3

####Array indexing and slicing

In [38]:
arr3 = np.array([
    [[11, 12, 13, 14],
     [13, 14, 15, 19]],

    [[15, 16, 17, 21],
     [63, 92, 36, 18]],

    [[98, 32, 81, 23],
     [17, 18, 19.5, 43]]])

In [39]:
arr3.shape

(3, 2, 4)

In [40]:
arr3[1, 1, 2]

36.0

In [42]:
arr3[1:,:1,1:]

array([[[16., 17., 21.]],

       [[32., 81., 23.]]])

####Other way of creating numpy array

In [44]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [45]:
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [46]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
#Random vector
np.random.rand(5)

array([0.43604834, 0.44603392, 0.95230217, 0.67925038, 0.50575541])

In [49]:
#Random Matrix
np.random.randn(2,3)

array([[ 0.28499355,  1.10839201, -0.24701322],
       [ 1.05193638,  1.3588554 ,  0.79742395]])

In [50]:
#fixed value
np.full((2,3),50)

array([[50, 50, 50],
       [50, 50, 50]])

In [51]:
#Range with start,end, difference
np.arange(10,50,4)

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46])

In [52]:
# Equally spaced numbers in a range
np.linspace(3, 27, 9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])