<a href="https://colab.research.google.com/github/Neethuharii/Foundatin-of-ML/blob/main/Linear%20Regression/Linear_Regression__Multivariate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [15]:
data=pd.read_csv('/content/homeprices-2.csv')
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [16]:
data.bedrooms.median()

4.0

In [17]:
data.bedrooms=data.bedrooms.fillna(data.bedrooms.median())

In [18]:
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [19]:
data1=data.drop('price',axis='columns')
data1

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [20]:
reg=linear_model.LinearRegression()
reg

LinearRegression()

In [21]:
price=data.price
price

0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: price, dtype: int64

In [22]:
reg.fit(data1,price)

LinearRegression()

Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old



In [23]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old



In [24]:
reg.predict([[2500,4,5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

##Excercise

In [25]:
hire_data=pd.read_csv('/content/hiring.csv')
hire_data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [26]:
hire_data.experience=hire_data.experience.fillna('Zero')

In [27]:
hire_data.experience

0      Zero
1      Zero
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [28]:
!pip install word2number

  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5568 sha256=09fe4f177aec3d924376675b00536225c58d05be996e27e51eb0c9c35880b9e4
  Stored in directory: /root/.cache/pip/wheels/84/ff/26/d3cfbd971e96c5aa3737ecfced81628830d7359b55fbb8ca3b
Successfully built word2number


In [29]:
from word2number import w2n

In [30]:
hire_data.experience = hire_data.experience.apply(w2n.word_to_num)
hire_data.experience

0     0
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: int64

In [31]:
import math
median_test_score = math.floor(hire_data['test_score(out of 10)'].mean())
median_test_score

7

In [32]:
hire_data['test_score(out of 10)'] = hire_data['test_score(out of 10)'].fillna(median_test_score)

In [33]:
hire_data['test_score(out of 10)']

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     7.0
7     7.0
Name: test_score(out of 10), dtype: float64

In [34]:
hire_data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [35]:
reg1=linear_model.LinearRegression()
reg1

LinearRegression()

In [36]:
hire_data1=hire_data.drop('salary($)',axis='columns')
hire_data1

experience  test_score(out of 10)  interview_score(out of 10)
0           0                    8.0                           9
1           0                    8.0                           6
2           5                    6.0                           7
3           2                   10.0                          10
4           7                    9.0                           6
5           3                    7.0                          10
6          10                    7.0                           7
7          11                    7.0                           8

In [37]:
salary = hire_data['salary($)']
salary

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [39]:
reg1.fit(hire_data1,salary)

LinearRegression()

2 yr experience, 9 test score, 6 interview score



In [41]:
reg1.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

12 yr experience, 10 test score, 10 interview score

In [42]:
reg1.predict([[12,10,10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])